# Generated by Django 5.1.4 on 2025-01-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cuisines', models.CharField(max_length=200)),
                ('rating', models.FloatField(max_length=20)),
                ('picture', models.URLField(default='https://tse1.mm.bing.net/th?id=OIP.5y5BZutjOh2A826vLFyj4QHaFW&pid=Api&P=0&h=180')),
            ],
        ),
    ]
