# Generated by Django 5.1.4 on 2025-01-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://tse2.mm.bing.net/th?id=OIP.DwONcWAkwxTR3KPZb0xM8AHaHa&pid=Api&P=0&h=180')),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=20)),
                ('is_veg', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='delivery.restaurant')),
            ],
        ),
    ]
